FROM performer_base
ADD ./modelling_dual_encoder_performer.py /workspace/modelling_dual_encoder_performer.py
ADD ./preprocessing.py /workspace/preprocessing.py
ADD ./utils.py /workspace/utils.py
ADD ./ds_config.json /workspace/ds_config.json
ADD ./setup.py /workspace/setup.py
ADD ./training.py /workspace/training.py
ADD ./evaluation.py /workspace/evaluation.py
ADD ./run.sh /workspace/run.sh
WORKDIR /
EXPOSE 6016
ENTRYPOINT ["bash","/workspace/run.sh"]