FROM deepspeed/deepspeed:v031_torch15_cuda101

WORKDIR /
EXPOSE 6016
ENTRYPOINT ["deepspeed", "/workspace/training_laper_deepspeed.py", "--deepspeed","--deepspeed_config", "/workspace/ds_config.json"]